### ISSUE TITLE
Hackathon : Setup DevOps env for public deploy

### ISSUE THREAD

**Issue by justinlewis** [RoaringForkTech/rft-operations#2]
We need someone to lead support for dev ops and deployment. The goal is to deploy simple apps by the end of Saturday. We don't know what the tech stacks are but if we need to for deployment and hosting reasons we can consider adding some restrictions. 

- [ ] Determine needs.  
- [ ] Share cost with Justin so he can raise money
- [ ] Setup initial infrastructure

**Comment by carrpet** [comment]
Are these going to be full stack web apps in general with persistence requirements?  I was thinking maybe Heroku will suit our needs?  It supports postgresql for persistence layer. Apps are hosted on a heroku subdomain. 

Here's the pricing model: https://www.heroku.com/pricing  If we have more information about the infrastructure requirements maybe we can hone in what we need here.  
We can always start with the free tier, depending on how many apps we have to start hosting on hackday.  I think the max is 5 VMS = 5 apps for the free tier.

**Comment by justinlewis** [comment]
@stevetarver, @jcerise, and I talked about this more the other day and are thinking that we shouldn't worry too much about true deployment for the sake of simplicity. We think there will be motivation to get something out if the motivation is high after the fact rather than making it a requirement. It still would be a good idea to think of a common hosting env for RFT where some of these could potentially live. Steve was recommending Digital Ocean. I've never used it. Have you?
